#!/usr/bin/env python3
import sys
import subprocess

def check_factor(*args):
    if len(args) != 3:
        args_list = list(args)
        count = 0
        num2 = 1
        for a in args_list:
            if count > 1:
                num2 *= int(a)
            count += 1
    else:
        num2 = args[2]

    num1 = args[1]
    num = args[0].replace(':', '=')

    result = 1 if int(num2) > int(num1) else 0
    if result == 1:
        numcp = num1
        num1 = num2
        num2 = numcp

    print(f"{num}{num1}*{num2}")

if len(sys.argv) != 2:
    print('Usage: python script.py <file>')
    exit(1)
else:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            result = subprocess.check_output(['factor', line.strip()]).decode('utf-8').strip()
            check_factor(*result.split())
